In [48]:
%pip install pandas
%pip install numpy
%pip install pyarrow
%pip install --upgrade pandas pyarrow

Requirement already satisfied: pandas in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (2.1.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pyarrow in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (22.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (2.3.3)
Requirement already satisfied: pyarrow in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (22.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [49]:
import pandas as pd
import numpy as np

file_path = '../data/techniques_classification/train.parquet'

df = pd.read_parquet(file_path)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3822 entries, 0 to 3821
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             3822 non-null   object
 1   content        3822 non-null   object
 2   lang           3822 non-null   object
 3   manipulative   3822 non-null   bool
 4   techniques     2589 non-null   object
 5   trigger_words  2589 non-null   object
dtypes: bool(1), object(5)
memory usage: 153.2+ KB

In [50]:
df.head(30)

,id,content,lang,manipulative,techniques,trigger_words
0,0bb0c7fa-101b-4583-a5f9-9d503339141c,Новий огляд мапи DeepState від російського вій...,uk,True,"[euphoria, loaded_language]","[[27, 63], [65, 88], [90, 183], [186, 308]]"
1,7159f802-6f99-4e9d-97bd-6f565a4a0fae,Недавно 95 квартал жёстко поглумился над русск...,ru,True,"[loaded_language, cherry_picking]","[[0, 40], [123, 137], [180, 251], [253, 274]]"
2,e6a427f1-211f-405f-bd8b-70798458d656,🤩\nТим часом йде евакуація Бєлгородського авто...,uk,True,"[loaded_language, euphoria]","[[55, 100]]"
3,1647a352-4cd3-40f6-bfa1-d87d42e34eea,В Україні найближчим часом мають намір посилит...,uk,False,None,None
4,9c01de00-841f-4b50-9407-104e9ffb03bf,"Расчёты 122-мм САУ 2С1 ""Гвоздика"" 132-й бригад...",ru,True,[loaded_language],"[[114, 144]]"
5,46493f44-f00a-4ffb-9cda-252ccf5fa4c6,"Апартаменти\n триповерхова келія Паші Лєбєдя, ...",uk,True,[loaded_language],"[[94, 108], [208, 227]]"
6,1417fffa-461c-4bf7-bea5-398e8ea5db81,"⚡️\nКитай надеется, что пакетное соглашение о ...",ru,False,None,None
7,f8021666-1636-4e1f-b8e3-535860eca5ce,До сьогоднішнього дня Джо Байден був у Києві п...,uk,True,"[loaded_language, glittering_generalities, eup...","[[65, 223], [225, 697]]"
8,ed5d2195-09b4-4837-82eb-b65244c8a7b2,⚡️\nПосле освобождения Соледара откроются благ...,ru,True,"[cherry_picking, cliche]","[[3, 66], [71, 94]]"
9,7d7504ff-295e-435d-b565-ed62d4eebaa0,Российское руководство сделало террор инструме...,ru,True,"[loaded_language, cherry_picking, appeal_to_fear]","[[0, 80], [1034, 1049], [1076, 1105], [1171, 1..."
10,69912f3c-29e5-40ac-a12d-0226e4971615,"Ну, что, расеянцы, повоевали с Украиной?\nА ес...",ru,True,"[loaded_language, appeal_to_fear, euphoria]","[[0, 17], [19, 28], [41, 64], [89, 114], [162,..."
11,cefabf69-dc9d-4102-9a9b-299cff60a293,❗️\nВСУ обстреляли гражданскую инфраструктуру ...,ru,False,None,None
12,f3c8b031-a058-4c94-b060-dfc8ef166bb6,Підари намагалися прорватися\n до населеного п...,uk,True,"[loaded_language, euphoria]","[[0, 6], [18, 28], [90, 117], [121, 147]]"
13,62d8357a-6f5f-4ee6-9469-650cf09848a6,"​​\nРуслан Стрілець: Після 10 років зволікань,...",uk,True,"[loaded_language, glittering_generalities, cli...","[[35, 44], [54, 74], [538, 575], [1338, 1502],..."
14,31bcfd31-ae0e-4109-b23b-6c16aa887196,🗳\nПервый день досрочного голосования на выбор...,ru,False,None,None
15,990fffce-73a0-4efb-b9dd-1f1fe7154750,Армия обороны Израиля внимательно следит за си...,ru,False,None,None
16,d987f555-8a59-409d-8d1d-543e4f337d17,Трагедия в трёх актах:\n1. \nУкраинские беженц...,ru,True,"[loaded_language, cherry_picking, cliche, euph...","[[0, 21], [27, 206], [211, 231], [233, 241]]"
17,b36492da-7885-4b31-9c6f-8cd21db8b0d1,Дай.\nhttps://peremogi.livejournal.com/6996369...,ru,True,[loaded_language],"[[53, 79], [83, 99], [115, 129]]"
18,9ae4cfa9-aa9e-49e5-80ab-e9777ebc77c6,Сцуко!!! Кращій стьоб над руснявою ескортницею...,uk,True,[loaded_language],"[[0, 5], [9, 146]]"
19,525d974a-88f2-4bc4-8442-28b6132abecf,​​\n👉\nВсеволод Князєв визнаний за протоколом ...,uk,False,None,None
20,c598905d-07f5-4bf0-9292-fb83111a4294,"Про очевидне. Але все ще не для всіх… Так от, ...",uk,True,"[glittering_generalities, appeal_to_fear]","[[120, 147], [149, 162], [164, 178], [180, 217..."
21,95052f18-a604-437f-a496-cc8db50de584,🫡\n Раджу підписатись на бойового товариша \n«...,uk,False,None,None
22,7a6b5b9f-dd3b-4b3d-9b18-32db8cc1cd22,📌\nУничтожение группы ВСУшников в Бахмуте арти...,ru,True,"[loaded_language, euphoria]","[[3, 116]]"
23,5a032cd7-ab92-4919-a144-ac428c9850f1,А ще краще — притягнути до відповідальності ти...,uk,True,[loaded_language],"[[0, 78]]"
24,19daeb3a-51ab-4899-811c-81b3460fc4ef,❗️\nНа розі вулиці Хрещатик та Бессарабської п...,uk,True,"[loaded_language, appeal_to_fear]","[[3, 94], [99, 165], [170, 206], [210, 273], [..."
25,482c72fd-f125-43cb-ba40-30ddb8073c85,"Верховний суд США постановив, що Дональд Трамп...",uk,False,None,None
26,1b9e8836-707c-4a8b-b093-7ccc11bdb10e,Припиніть безжально знищувати екосистему Украї...,uk,True,"[glittering_generalities, bandwagon, loaded_la...","[[10, 40], [218, 249], [322, 340], [433, 456]]"
27,9804e4c4-818f-4579-b38a-8d694f8bddda,Полонений військовослужбовець 72 ОМСБр Шилін ...,uk,True,[euphoria],"[[86, 138], [181, 466]]"
28,b3381db7-28ac-4f0d-8206-8e5f2e68e609,В Центрально-Городском районе Горловки состоял...,ru,False,None,None
29,a7979f8a-c586-4d72-aae2-1d80323b7a0e,"🇺🇦\nУкраине нужны солдаты, а не учёные\n🤦\nВУЗ...",ru,True,"[loaded_language, fud, appeal_to_fear]","[[3, 37], [40, 211], [307, 386]]"

In [51]:
%pip install datasets transformers scikit-learn beautifulsoup4 pyarrow

import ast
import joblib
from bs4 import BeautifulSoup
from sklearn.preprocessing import MultiLabelBinarizer
from datasets import load_dataset, Dataset
import os

Requirement already satisfied: datasets in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (4.4.1)
Requirement already satisfied: transformers in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (4.57.3)
Requirement already satisfied: scikit-learn in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (1.7.2)
Requirement already satisfied: beautifulsoup4 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (4.14.2)
Requirement already satisfied: pyarrow in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (22.0.0)
Requirement already satisfied: filelock in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from datasets) (3.20.0)
Requirement already satisfied: numpy>=1.17 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from datasets) (2.1.3)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from datasets) (0.4.0)
Requirement already satisfied: pandas in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from datasets) (2.32.3)
Requirement already satisfied: httpx<1.0.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from datasets) (0.70.18)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2025.10.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from datasets) (0.36.0)
Requirement already satisfied: packaging in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from datasets) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from beautifulsoup4) (4.12.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: anyio in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from httpx<1.0.0->datasets) (4.11.0)
Requirement already satisfied: certifi in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from httpx<1.0.0->datasets) (2024.8.30)
Requirement already satisfied: httpcore==1.* in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from httpx<1.0.0->datasets) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from requests>=2.32.2->datasets) (3.4.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from requests>=2.32.2->datasets) (2.2.3)
Requirement already satisfied: colorama in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\admin\desktop\python_lab_3_and_4\python_lab_3_and_4\venv\lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [52]:
def parse_offsets(offsets_data):
    if offsets_data is None:
        return []
    
    if isinstance(offsets_data, (list, np.ndarray)):
        if len(offsets_data) == 0:
            return []
        return offsets_data

    try:
        if pd.isna(offsets_data):
            return []
    except ValueError:
        pass

    if isinstance(offsets_data, str):
        if not offsets_data.strip():
            return []
        try:
            return ast.literal_eval(offsets_data)
        except (ValueError, SyntaxError):
            return []
            
    return []


def clean_token_str(token):
    if re.match(r'http[s]?://\S+', token):
        return '[url]'
    
    cleaned = re.sub(r'[^\w\s,.:;!?@\'"()-]', '', token, flags=re.UNICODE)
    
    return cleaned.lower().strip()


def safe_eval_techniques(tech_str):
    if not tech_str or str(tech_str).lower() in ('none', 'nan', '[]'):
        return []
    
    s = str(tech_str)
    
    s = s.replace('[', ' ').replace(']', ' ').replace("'", ' ').replace('"', ' ').replace(',', ' ')
    tokens = s.split()
    
    return [t.strip().lower() for t in tokens if len(t) > 1 and not t.isdigit()]

In [53]:
import re
def process_row(row):
    
    raw_text = row['content']
    triggers_data = row['trigger_words']
    
    if not raw_text or pd.isna(raw_text):
        return "", []

    trigger_ranges = parse_offsets(triggers_data)
    
    final_tokens = []
    final_labels = []

    for match in re.finditer(r'\S+', raw_text):
        token_raw = match.group()
        start, end = match.span() 
        
        is_trigger = 0
        for (t_start, t_end) in trigger_ranges:
            if start < t_end and end > t_start:
                is_trigger = 1
                break
        
        token_clean = clean_token_str(token_raw)
        
        if token_clean:
            final_tokens.append(token_clean)
            final_labels.append(is_trigger)
            
    cleaned_full_text = " ".join(final_tokens)
    
    return pd.Series([cleaned_full_text, final_labels])

In [54]:
mlb_path = './multilabel_binarizer.pkl'

df[['cleaned_content', 'token_labels']] = df.apply(process_row, axis=1)
df['techniques'] = df['techniques'].fillna('').astype(str)
df['techniques_list'] = df['techniques'].apply(safe_eval_techniques)

mlb = MultiLabelBinarizer()
mlb.fit(df['techniques_list'])
binary_matrix = mlb.transform(df['techniques_list'])

techniques_df = pd.DataFrame(binary_matrix, columns=mlb.classes_)

joblib.dump(mlb, mlb_path)
print(f"Знайдено класів технік: {len(mlb.classes_)}")
print(f"Класи: {mlb.classes_}")


df_final = pd.concat([df[['id', 'cleaned_content', 'token_labels']], techniques_df], axis=1)

hf_dataset = Dataset.from_pandas(df_final)

sample_with_trigger = df_final[df_final['token_labels'].apply(lambda x: 1 in x if isinstance(x, list) else False)].head(1)

Знайдено класів технік: 10
Класи: ['appeal_to_fear' 'bandwagon' 'cherry_picking' 'cliche' 'euphoria' 'fud'
 'glittering_generalities' 'loaded_language' 'straw_man' 'whataboutism']

In [55]:
df_final.head()

,id,cleaned_content,token_labels,appeal_to_fear,bandwagon,cherry_picking,cliche,euphoria,fud,glittering_generalities,loaded_language,straw_man,whataboutism
0,0bb0c7fa-101b-4583-a5f9-9d503339141c,новий огляд мапи deepstate від російського вій...,"[0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",0,0,0,0,1,0,0,1,0,0
1,7159f802-6f99-4e9d-97bd-6f565a4a0fae,недавно 95 квартал жёстко поглумился над русск...,"[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,0,1,0,0,0,0,1,0,0
2,e6a427f1-211f-405f-bd8b-70798458d656,тим часом йде евакуація бєлгородського автовок...,"[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, ...",0,0,0,0,1,0,0,1,0,0
3,1647a352-4cd3-40f6-bfa1-d87d42e34eea,в україні найближчим часом мають намір посилит...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,0,0,0,0,0,0,0,0,0
4,9c01de00-841f-4b50-9407-104e9ffb03bf,"расчёты 122-мм сау 2с1 ""гвоздика"" 132-й бригад...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,0,0,0,0,0,0,1,0,0